complete limit size stream
js-tasks-ru/nodejs-20210618_haliont pull request #3
Opened 2021-07-01 18:19 UTC by Haliont

2021-07-01 18:20 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-07-04 21:08 UTC, tadjik1 commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +    const chunksByteLength = Buffer.concat(this.chunks).byteLength;
здесь не нужно сохранять все передаваемые чанки в памяти - это может привести к проблемам с ресурсами. вместо этого нужно получать размер каждого чанка и складывать эти числа, таким образом сами данные не будут оставаться в памяти

2021-07-04 21:09 UTC, tadjik1 requested changes
@Haliont в целом хорошее решение, идею уловили правильно, но нужно немного доработать определение ситуации превышения лимита

2021-07-08 17:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-08 18:08 UTC, tadjik1 approved these changes
👍

2021-07-08 18:08 UTC, merged